### ISSUE TITLE
Unable to run the Example

### ISSUE THREAD

**Issue by shorbenko** [uhnmdi/CCGlucose#2]
After checkout and 'pod install' I received an error:
> Cloning spec repo `ehealthinnovation-phit-cocoapods` from `https://github.ehealthinnovation.org/PHIT/CocoaPods.git`
> [!] Unable to add a source with url `https://github.ehealthinnovation.org/PHIT/CocoaPods.git` named `ehealthinnovation-phit-cocoapods`.
> You can try adding it manually in `~/.cocoapods/repos` or via `pod repo add`.

**Comment by shorbenko** [comment]
The workaround is to set source explicitly for pods
```
 pod 'CCBluetooth', :git => 'https://github.com/uhnmdi/CCBluetooth.git'
 pod 'CCToolbox', :git => 'https://github.com/uhnmdi/CCToolbox.git'
```

**Comment by ktallevi** [comment]
Issue fixed, podfile updated.
